<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KalkelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('kalkels')->insert([
            //1. KAB BANTUL KAPANEWON BAMBANGLIPURO [1]
            // 'MULYODADI'// 'SIDOMULYO'// 'SUMBERMULYO'

            //2. KAB BANTUL KAPANEWON BANGUNTAPAN [2]
            // 'BANGUNTAPAN','BATURETNO','JAGALAN','JAMBIDAN','POTORONO','SINGOSAREN','TAMANAN','WIROKERTEN',

            //3. KAB BANTUL KAPANEWON BANTUL [3]
            // 'BANTUL', 'PALBAPANG','RINGINHARJO','SABDODADI','TRIRENGGO',

            //4. KAB BANTUL KAPANEWON DLINGO [4]
            // 'DLINGO','JATIMULYO','MANGUNAN','MUNTUK','TEMUWUH','TERONG',

            //5. KAB BANTUL KAPANEWON IMOGIRI [5]
            //'GIRIREJO','IMOGIRI','KARANGTALUN','KARANGTENGAH','KEBONAGUNG','SELOPAMIORO','SRIHARJO','WUKIRSARI',

            //6. KAB BANTUL KAPANEWON JETIS [6]
            //'CANDEN','PATALAN','SUMBERAGUNG','TRIMULYO',

            //7. KAB BANTUL KAPANEWON KASIHAN [7]
            //'BANGUNJIWO','NGESTIHARJO','TAMANTIRTO','TIRTONIRMOLO',

            //8. KAB BANTUL KAPANEWON KRETEK [8]
            //'DONOTIRTO','PARANGTRITIS','TIRTOHARGO','TIRTOMULYO','TIRTOSARI',

            //9. KAB BANTUL KAPANEWON PAJANGAN [9]
            //'GUWOSARI','SENDANGSARI','TRIWIDADI',

            //10. KAB BANTUL KAPANEWON PANDAK [10]
            //'CATURHARJO','GILANGHARJO','TRIHARJO','WIJIREJO',

            //11. KAB BANTUL KAPANEWON PIYUNGAN [11]
            //'SITIMULYO','SRIMARTANI','SRIMULYO',

            //12. KAB BANTUL KAPANEWON PLERET [12]
            //'BAWURAN','PLERED','SEGOROYOSO','WONOKROMO','WONOLELO',

            //13. KAB BANTUL KAPANEWON PUNDONG [13]
            //'PANJANGREJO','SELOHARJO','SRIHARDONO',

            //14. KAB BANTUL KAPANEWON SANDEN [14]
            //'GADINGHARJO','GADINGSARI','MURTIGADING','SRIGADING',

            //15. KAB BANTUL KAPANEWON SEDAYU [15]
            //'ARGODADI','ARGOMULYO','ARGOREJO','ARGOSARI',

            //16. KAB BANTUL KAPANEWON SEWON [16]
            //'BANGUNHARJO','PANGGUNGHARJO','PENDOWOHARJO','TIMBULHARJO',

            //17. KAB BANTUL KAPANEWON SRANDAKAN [17]
            //'PONCOSARI','TRIMURTI',

            // ---------------------------------------------------------------------
            //1. KAB GUNUNGKIDUL KAPANEWON GEDANGSARI [18]
            //'HARGOMULYO','MERTELU','NGALANG','SAMPANG','SERUT','TEGALREJO','WATUGAJAH',

            //2. KAB GUNUNGKIDUL KAPANEWON GIRISUBO [19]
            //'BALONG','JEPITU','JERUKWUDEL','KARANGAWEN','NGLINDUR','PUCUNG','SONGBANYU','TILENG',

            //3. KAB GUNUNGKIDUL KAPANEWON KARANGMOJO [20]
            //'BEJIHARJO','BENDUNGAN','GEDANGREJO','JATIAYU','KARANGMOJO','KELOR','NGAWIS','NGIPAK','WILADEG',

            //4. KAB GUNUNGKIDUL KAPANEWON NGAWEN [21]
            //'BEJI','JURANGJERO','KAMPUNG','SAMBIREJO','TANCEP','WATUSIGAR',

            //5. KAB GUNUNGKIDUL KAPANEWON NGLIPAR [22]
            //'KATONGAN','KEDUNGKERIS','KEDUNGPOH','NATAH','NGLIPAR','PENGKOL','PILANGREJO',

            //6. KAB GUNUNGKIDUL KAPANEWON PALIYAN [23]
            //'GIRING','GROGOL','KARANGASEM','KARANGDUWET','MULUSAN','PAMPANG','SODO',

            //7. KAB GUNUNGKIDUL KAPANEWON PANGGANG [24]
            //'GIRIHARJO','GIRIKARTO','GIRIMULYO','GIRISEKAR','GIRISUKO','GIRIWUNGU',

            //8. KAB GUNUNGKIDUL KAPANEWON PATUK [25]
            //'BEJI','BUNDER','NGLANGGERAN','NGLEGI','NGORO-ORO','PATUK','PENGKOK','PUTAT','SALAM','SEMOYO','TERBAH',

            //9. KAB GUNUNGKIDUL KAPANEWON PLAYEN [26]
            //'BANARAN','BANDUNG','BANYUSOCO','BLEBERAN','DENGOK','GADING','GETAS','LOGANDENG','NGAWU','NGLERI','NGUNUT',
            //'PLAYEN','PLEMBUTAN',

            //10. KAB GUNUNGKIDUL KAPANEWON PONJONG [27]
            //'BEDOYO','GENJAHAN','GOMBANG','KARANGASEM','KENTENG','PONJONG','SAWAHAN','SIDOREJO','SUMBERGIRI','TAMBAKROMO',
            //'UMBULREJO',

            //11. KAB GUNUNGKIDUL KAPANEWON PURWOSARI [28]
            //'GIRIASIH','GIRICAHYO','GIRIJATI','GIRIPURWO','GIRITIRTO',

            //12. KAB GUNUNGKIDUL KAPANEWON RONGKOP [29]
            //'BOHOL','BOTODAYAKAN','KARANGWUNI','MELIKAN','PETIR','PRINGOMBO','PUCANGANOM','SEMUGIH',

            //13. KAB GUNUNGKIDUL KAPANEWON SAPTOSARI [30]
            //'JETIS','KANIGORO','KEPEK','KRAMBILSAWIT','MONGGOL','NGLORA','PLANJAN',

            //14. KAB GUNUNGKIDUL KAPANEWON SEMANU [31]
            //'CANDIREJO','DADAPAYU','NGEPOSARI','PACAREJO','SEMANU',

            //15. KAB GUNUNGKIDUL KAPANEWON SEMIN [32]
            //'BENDUNG','BULUREJO','CANDIREJO','KALITEKUK','KARANGSARI','KEMEJING','PUNDUNGSARI','REJOSARI','SEMIN',
            //'SUMBEREJO',

            //16. KAB GUNUNGKIDUL KAPANEWON TANJUNGSARI [33]
            //'BANJAREJO','HARGOSARI','KEMADANG','KEMIRI','NGESTIREJO',

            //17. KAB GUNUNGKIDUL KAPANEWON TEPUS [34]
            //'GIRIPANGGUNG','PURWODADI','SIDOHARJO','SUMBERWUNGU','TEPUS',

            //18. KAB GUNUNGKIDUL KAPANEWON WONOSARI [35]
            //'BALEHARJO','DUWET','GARI','KARANGTENGAH','KARANGREJEK','KEPEK','MULO','PIYAMAN','PULUTAN',
            //'SELANG','SIRAMAN','WARENG','WONOSARI','WUNUNG',

            // ---------------------------------------------------------------------
            //1. KAB KULONPROGO KAPANEWON GALUR [36]
            //'BANARAN','BROSOT','KARANGSEWU','KRANGGAN','NOMPOREJO','PANDOWAN','TIRTORAHAYU',

            //2. KAB KULONPROGO KAPANEWON GIRIMULYO [37]
            //'GIRIPURWO','JATIMULYO','PENDOWOREJO','PURWOSARI',

            //3. KAB KULONPROGO KAPANEWON KALIBAWANG [38]
            //'BANJARARUM','BANJARHARJO','BANJAROYO','BANJARSARI',

            //4. KAB KULONPROGO KAPANEWON KOKAP [39]
            //'HARGOMULYO','HARGOREJO','HARGOTIRTO','HARGOWILIS','KALIREJO',

            //5. KAB KULONPROGO KAPANEWON LENDAH [40]
            //'BUMIREJO','GULUREJO','JATIREJO','NGENTAKREJO','SIDOREJO','WAHYUHARJO',

            //6. KAB KULONPROGO KAPANEWON NANGGULAN [41]
            //'BANYUROTO','DONOMULYO','JATISARONO','KEMBANG','TANJUNGHARJO','WIJIMULYO',

            //7. KAB KULONPROGO KAPANEWON PANJATAN [42]
            //'BOJONG','BUGEL','CERME','DEPOK','GARONGAN','GOTAKAN','KANOMAN','KREMBANGAN','PANJATAN','PLERET','TAYUBAN',

            //8. KAB KULONPROGO KAPANEWON PENGASIH [43]
            //'KARANGSARI','KEDUNGSARI','MARGOSARI','PENGASIH','SENDANGSARI','SIDOMULYO','TAWANGSARI',

            //9. KAB KULONPROGO KAPANEWON SAMIGALUH [44]
            //'BANJARSARI','GERBOSARI','KEBONHARJO','NGARGOSARI','PAGERHARJO','PURWOHARJO','SIDOHARJO',

            //10. KAB KULONPROGO KAPANEWON SENTOLO [45]
            //'BANGUNCIPTO','DEMANGREJO','KALIAGUNG','SALAMREJO','SENTOLO','SRIKAYANGAN','SUKORENO','TUKSONO',

            //11. KAB KULONPROGO KAPANEWON TEMON [46]
            //'DEMEN','GLAGAH','JANGKARAN','JANTEN','KALIDENGEN','KALIGINTUNG','KARANGWULUH','KEBONREJO','KEDUNDANG',
            //'KULUR','PALIHAN','PLUMBON','SINDUTAN','TEMONKULON','TEMONWETAN',

            //12. KAB KULONPROGO KAPANEWON WATES [47]
            //'BENDUNGAN','GIRIPENI','KALIWARU','KARANGWUNI','NGESTIHARJO','SOGAN','TRIHARJO','WATES',



            // ---------------------------------------------------------------------
            //1. KAB SLEMAN KAPANEWON BERBAH [48]
            //JOGOTIRTO','KALITIRTO','SENDANGTIRTO','TEGALTIRTO',

            //2. KAB SLEMAN KAPANEWON CANGKRINGAN [49]
            //'ARGOMULYO','GLAGAHARJO','KEPUHARJO','UMBULHARJO','WUKIRSARI',

            //3. KAB SLEMAN KAPANEWON DEPOK [50]
            //'CATURTUNGGAL','CONDONGCATUR','MAGUWOHARJO',

            //4. KAB SLEMAN KAPANEWON GAMPING [51]
            //'AMBARKETAWANG','BALECATUR','BANYURADEN','NOGOTIRTO','TRIHANGGO',

            //5. KAB SLEMAN KAPANEWON GODEAN [52]
            //'SIDOAGUNG','SIDOARUM','SIDOKARTO','SIDOLUHUR','SIDOMOYO','SIDOMULYO','SIDOREJO',

            //6. KAB SLEMAN KAPANEWON KALASAN [53]
            //'PURWOMARTANI','SELOMARTANI','TAMANMARTANI','TIRTOMARTANI',

            //7. KAB SLEMAN KAPANEWON MINGGIR [54]
            //'SENDANGAGUNG','SENDANGARUM','SENDANGMULYO','SENDANGREJO','SENDANGSARI',

            //8. KAB SLEMAN KAPANEWON MLATI [55]
            //'SENDANGADI','SINDUADI','SUMBERADI','TIRTOADI','TLOGOADI',

            //9. KAB SLEMAN KAPANEWON MOYUDAN [56]
            //'SUMBERSARI','SUMBERAGUNG','SUMBERARUM','SUMBERRAHAYU',

            //10. KAB SLEMAN KAPANEWON NGAGLIK [57]
            //'DONOHARJO','MINOMARTANI','SARDONOHARJO','SARIHARJO','SINDUHARJO','SUKOHARJO',

            //11. KAB SLEMAN KAPANEWON NGEMPLAK [58]
            //'BIMOMARTANI','SINDUMARTANI','UMBULMARTANI','WEDOMARTANI','WIDODOMARTANI',

            //12. KAB SLEMAN KAPANEWON PAKEM [59]
            //'CANDIBINANGUN','HARGOBINANGUN','HARJOBINANGUN','PAKEMBINANGUN','PURWOBINANGUN',

            //13. KAB SLEMAN KAPANEWON PRAMBANAN [60]
            //'BOKOHARJO','GAYAMHARJO','MADUREJO','SAMBIREJO','SUMBERHARJO','WUKIRHARJO',

            //14. KAB SLEMAN KAPANEWON SEYEGAN [61]
            //'MARGOAGUNG','MARGODADI','MARGOKATON','MARGOLUWIH','MARGOMULYO',

            //15. KAB SLEMAN KAPANEWON SLEMAN [62]
            //'CATURHARJO','PANDOWOHARJO','TRIDADI','TRIHARJO','TRIMULYO',

            //16. KAB SLEMAN KAPANEWON TEMPEL [63]
            //'BANYUREJO','LUMBUNGREJO','MARGOREJO','MERDIKOREJO','MOROREJO','PONDOKREJO','SUMBERREJO','TAMBAKREJO',

            //17. KAB SLEMAN KAPANEWON TURI [64]
            //'BANGUNKERTO','DONOKERTO','GIRIKERTO','WONOKERTO',

            // ---------------------------------------------------------------------
            //1. KOTA YOGYAKARTA KEMANTREN DANUREJAN [65]
            //'BAUSASRAN','SURYATMAJAN','TEGALPANGGUNG',

            //2. KOTA YOGYAKARTA KEMANTREN GEDONGTENGEN [66]
            //'PRINGGOKUSUMAN','SOSROMENDURAN',

            //3. KOTA YOGYAKARTA KEMANTREN GONDOKUSUMAN [67]
            //'BACIRO','DEMANGAN','KLITREN','KOTABARU','TERBAN',

            //4. KOTA YOGYAKARTA KEMANTREN GONDOMANAN [68]
            //'NGUPASAN','PRAWIRODIRJAN',

            //5. KOTA YOGYAKARTA KEMANTREN JETIS [69]
            //'BUMIJO','COKRODININGRATAN','GOWONGAN',

            //6. KOTA YOGYAKARTA KEMANTREN KOTAGEDE [70]
            //'PRENGGAN','PURBAYAN','REJOWINANGUN',

            //7. KOTA YOGYAKARTA KEMANTREN KRATON [71]
            //'KADIPATEN','PANEMBAHAN','PATEHAN',

            //8. KOTA YOGYAKARTA KEMANTREN MANTRIJERON [72]
            //'GEDONGKIWO','MANTRIJERON','SURYODININGRATAN',

            //9. KOTA YOGYAKARTA KEMANTREN MERGANGSAN [73]
            //'BRONTOKUSUMAN','KEPARAKAN','WIROGUNAN',

            //10. KOTA YOGYAKARTA KEMANTREN NGAMPILAN [74]
            //'NGAMPILAN','NOTOPRAJAN',

            //11. KOTA YOGYAKARTA KEMANTREN PAKUALAMAN [75]
            //'GUNUNGKETUR','PURWOKINANTI',

            //12. KOTA YOGYAKARTA KEMANTREN TEGALREJO [76]
            //'BENER','KARANGWARU','KRICAK','TEGALREJO',

            //13. KOTA YOGYAKARTA KEMANTREN UMBULHARJO [77]
            //'GIWANGAN','MUJAMUJU','PANDEYAN','SEMAKI','SOROSUTAN','TAHUNAN','WARUNGBOTO',

            //14. KOTA YOGYAKARTA KEMANTREN WIROBRAJAN [78]
            //'PAKUNCEN','PATANGPULUHAN','WIROBRAJAN',
        ]);
    }
}
